// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class CargoManipulator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Solenoid cargoSolenoid1;
    private Solenoid cargoSolenoid2;
    private DigitalInput cargoDigitalInput1;
    private DigitalInput cargoDigitalInput2;
    private DigitalInput cargoDigitalInput3;
    private Spark cargoSpeedController1;
    private Spark cargoSpeedController2;
    private Spark cargoSpeedController3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public CargoManipulator() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        cargoSolenoid1 = new Solenoid(0, 0);
        addChild("Cargo Solenoid 1",cargoSolenoid1);
        
        
        cargoSolenoid2 = new Solenoid(0, 1);
        addChild("Cargo Solenoid 2",cargoSolenoid2);
        
        
        cargoDigitalInput1 = new DigitalInput(0);
        addChild("Cargo Digital Input 1",cargoDigitalInput1);
        
        
        cargoDigitalInput2 = new DigitalInput(1);
        addChild("Cargo Digital Input 2",cargoDigitalInput2);
        
        
        cargoDigitalInput3 = new DigitalInput(2);
        addChild("Cargo Digital Input 3",cargoDigitalInput3);
        
        
        cargoSpeedController1 = new Spark(0);
        addChild("Cargo Speed Controller 1",cargoSpeedController1);
        cargoSpeedController1.setInverted(false);
        
        cargoSpeedController2 = new Spark(1);
        addChild("Cargo Speed Controller 2",cargoSpeedController2);
        cargoSpeedController2.setInverted(false);
        
        cargoSpeedController3 = new Spark(2);
        addChild("Cargo Speed Controller 3",cargoSpeedController3);
        cargoSpeedController3.setInverted(false);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

